# Generated by Django 5.2.1 on 2025-05-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LessonReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('lesson_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('time', models.TimeField()),
            ],
        ),
    ]
