# Generated by Django 5.2.1 on 2025-05-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonreminder',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
